use std::env;
use std::fs;
use std::io::Cursor;
use std::process::{Command, Stdio};
use flate2::read::GzDecoder;
use tar::Archive;
use tempfile::tempdir;

// This file will be generated by the panel_build.sh script
const BUNDLE: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/bundle.tar.gz"));

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("Starting KS Panel v5...");

    // Create a temporary directory to extract the bundle
    let dir = tempdir()?;
    let path = dir.path();

    // Extract the bundle
    let tar = GzDecoder::new(Cursor::new(BUNDLE));
    let mut archive = Archive::new(tar);
    archive.unpack(path)?;

    // Set the PORT environment variable to 8080 if not already set
    if env::var("PORT").is_err() {
        env::set_var("PORT", "8080");
    }

    // Path to the bundled node binary and the backend entry point
    #[cfg(windows)]
    let node_bin = path.join("node.exe");
    #[cfg(not(windows))]
    let node_bin = path.join("node");

    let entry_point = path.join("backend/src/index.js");

    // Make sure node is executable on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&node_bin)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&node_bin, perms)?;
    }

    // Run the backend
    let mut child = Command::new(node_bin)
        .arg(entry_point)
        .current_dir(path)
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .spawn()?;

    let port = env::var("PORT").unwrap_or_else(|_| "8080".to_string());
    println!("KS Panel is now running on port {}", port);

    let status = child.wait()?;

    if !status.success() {
        eprintln!("KS Panel exited with an error.");
        std::process::exit(status.code().unwrap_or(1));
    }

    Ok(())
}
