name: Panel

on:
  push:
    branches:
      - main
    paths:
      - 'panel/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(jq -r .version panel/package.json)
          echo "Version found: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create tar.xz of repository
        run: |
          TAR_NAME="panel.tar.xz"
          echo "Creating tar.xz file $TAR_NAME"
          cd panel
          tar --exclude='.git' -cJf "../$TAR_NAME" .
          cd ..
          echo "TAR_NAME=$TAR_NAME" >> $GITHUB_ENV

      - name: Ensure release exists
        run: |
          if ! gh release view "$VERSION" > /dev/null 2>&1; then
            echo "Release $VERSION not found, creating..."
            gh release create "$VERSION" -t "$VERSION" -n "Automated release for version $VERSION"
          else
            echo "Release $VERSION already exists."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload tar.xz to release
        run: |
          gh release upload "$VERSION" "$TAR_NAME" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
