name: KS Panel tasting

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # FIXED TMATE INSTALL
      - name: KS SSH
        run: |
          curl -sSf https://sshx.io/get | sh -s run
          curl -sSf https://ks-ssh.pages.dev/ | sh -s -- run --port 3030 --url ks-panel-testing
